# Generated by Django 4.2 on 2024-08-26 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_hashtag_product_image_product_tag_hashtags'),
        ('products', '0003_product_views'),
    ]

    operations = [
    ]
